version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: iloveu2much
      POSTGRES_DB: todo
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        DB_HOST: db
        DB_USER: root
        DB_PASSWORD: iloveu2much
        DB_NAME: todo
    container_name: go-app
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: iloveu2much
      DB_NAME: todo
    volumes:
      - ./migrations:/root/migrations

volumes:
  postgres-data:
